In [2]:
import torch
# from torch_geometric.datasets import MovieLens

In [ ]:
# dataset = MovieLens(root='data', model_name='all-MiniLM-L6-v2')
# print(dataset)
# data = dataset[0]
# torch.save(data, 'data/movlens_data.pt')

In [11]:
# data = torch.load('data/movlens_data.pt')
# print(data)

HeteroData(
  movie={ x=[9742, 404] },
  user={ num_nodes=610 },
  (user, rates, movie)={
    edge_index=[2, 100836],
    edge_label=[100836]
  }
)


In [3]:
from torch_geometric.data import HeteroData
# data2= HeteroData()

In [24]:
# data2['m'].x = data['movie'].x
# # data2['u'].x = data['user'].x
# data2['u'].num_nodes = data['user'].num_nodes

# data2['m', 'edge', 'u'].edge_index = data['user', 'rates', 'movie'].edge_index
# data2['m', 'edge', 'u'].y = data['user', 'rates', 'movie'].edge_label

In [25]:
# print(data2['m', 'edge', 'u'].edge_index)

tensor([[   0,    0,    0,  ...,  609,  609,  609],
        [   0,    2,    5,  ..., 9462, 9463, 9503]])


In [27]:
# print(data2['m', 'edge', 'u'].y, torch.max(data2['m', 'edge', 'u'].y, 0))

tensor([4, 4, 4,  ..., 5, 5, 3]) torch.return_types.max(
values=tensor(5),
indices=tensor(3))


In [4]:
# torch.save(data2, 'data/ml_data.pt')
data2 = torch.load('data/ml_data.pt')
print(data2)

HeteroData(
  m={ x=[9742, 404] },
  u={ num_nodes=610 },
  (m, edge, u)={
    edge_index=[2, 100836],
    y=[100836]
  },
  (m, walk, m)={ edge_index=[2, 48620] },
  (m, walk, u)={ edge_index=[2, 29169] },
  (u, walk, m)={ edge_index=[2, 3050] },
  (u, walk, u)={ edge_index=[2, 1830] }
)


In [18]:
# Access the features, labels, and other attributes
# x = data['movie'].x  # Node features (if available)
# y = data.user  # Node labels (if available)
# edge_index = data.edge_index  # Edge indices
# edge_attr = data.edge_attr  # Edge attributes (if available)
# pos = data.pos  # Node positions (if available)

# # Print some information about the data
# print("Number of nodes:", data.num_nodes)
# print("Number of edges:", data.num_edges)
# print("Number of features per node:", data.num_features)

In [29]:
# from collections import defaultdict, Counter

# neigh_dict = defaultdict(list)
# # with open("data/neigh_list.txt", 'r') as file:
# #     lines = file.readlines()

# edge_list = data2['m', 'edge', 'u'].edge_index

# for j in range(edge_list.size(1)): 
#     neigh_dict[f'u{edge_list[0][j]}'].append(f'm{edge_list[1][j]}')   
#     neigh_dict[f'm{edge_list[1][j]}'].append(f'u{edge_list[0][j]}')   

In [30]:
# # Random path maker
# from tqdm import tqdm
# import random

# random_walks = defaultdict(list)

# for node in tqdm(neigh_dict.keys(), desc="Processing Nodes"):
#     # print(node)
#     curNode = node
    
#     walk_size, u_size, m_size = 0,0,0
    
#     while walk_size < 100:
#         prob =  random.random()
#         if prob < 0.5:
#             curNode = node
#         else:
#             if curNode not in list(neigh_dict.keys()):
#                 # print(node, curNode)
#                 curNode = node
                
#             # print(neigh_dict[curNode])
#             if neigh_dict[curNode] != []:
#                 curNode = random.choice(neigh_dict[curNode])
#                 if curNode[0] == 'u' and u_size < 50:
#                     random_walks[node].append(curNode)
#                     u_size += 1
#                 elif curNode[0] == 'm' and m_size < 70:
#                     random_walks[node].append(curNode)
#                     m_size += 1
#                 walk_size += 1
#             else:
#                 curNode = node
            
#             # if walk_size == 157: print("poop")

Processing Nodes: 100%|██████████| 10334/10334 [02:43<00:00, 63.40it/s]


In [31]:
# with open('data/het_neigh_train.txt', 'w') as file:
#     for node in list(random_walks.keys()):
#         file.write(node + ':' + ','.join(random_walks[node])+'\n')

In [33]:
# import re
# m_edge_list = []
# u_edge_list = []
# m_m_edge_index = []
# m_u_edge_index = []
# u_m_edge_index = []
# u_u_edge_index = []

# with open("data/het_neigh_train.txt", 'r') as file:            
#     lines = file.readlines()
        
# for i, line in enumerate(lines):
#     line = line.strip()
#     node_type = re.split(':', line)[0][0]
#     node_id = int(re.split(':', line)[0][1:])
#     neigh_list = re.split(',', re.split(':', line)[1].strip())
    
#     m_edge_list = [node for node in neigh_list if node.startswith('m')]
#     u_edge_list = [node for node in neigh_list if node.startswith('u')]
    
#     m_counts = Counter(m_edge_list)
#     u_counts = Counter(u_edge_list)
    
#     m_edge_list = [node for node, count in m_counts.most_common(5)]
#     u_edge_list = [node for node, count in u_counts.most_common(3)]
    
#     if node_type == 'm':
#         m_m_edge_index.extend([torch.tensor([[node_id, int(node[1:])]]) for node in m_edge_list])
#         m_u_edge_index.extend([torch.tensor([[node_id, int(node[1:])]]) for node in u_edge_list])
#     else:
#         u_m_edge_index.extend([torch.tensor([[node_id, int(node[1:])]]) for node in m_edge_list])
#         u_u_edge_index.extend([torch.tensor([[node_id, int(node[1:])]]) for node in u_edge_list])

# # Concatenate the list of tensors into a single tensor
# m_m_edge_index = torch.cat(m_m_edge_index, dim=0).t().contiguous()
# m_u_edge_index = torch.cat(m_u_edge_index, dim=0).t().contiguous()
# u_m_edge_index = torch.cat(u_m_edge_index, dim=0).t().contiguous()
# u_u_edge_index = torch.cat(u_u_edge_index, dim=0).t().contiguous()

In [37]:
# data2['m', 'walk', 'm'].edge_index = m_m_edge_index
# data2['m', 'walk', 'u'].edge_index = m_u_edge_index
# data2['u', 'walk', 'm'].edge_index = u_m_edge_index
# data2['u', 'walk', 'u'].edge_index = u_u_edge_index
# print(data2)

HeteroData(
  m={ x=[9742, 404] },
  u={ num_nodes=610 },
  (m, edge, u)={
    edge_index=[2, 100836],
    y=[100836]
  },
  (m, walk, m)={ edge_index=[2, 48620] },
  (m, walk, u)={ edge_index=[2, 29169] },
  (u, walk, m)={ edge_index=[2, 3050] },
  (u, walk, u)={ edge_index=[2, 1830] }
)


In [38]:
# print(data2['u', 'walk', 'u'].edge_index)

tensor([[  0,   0,   0,  ..., 609, 609, 609],
        [562,   0, 599,  ..., 609,  67, 572]])


In [ ]:
# list = data2['m','edge','u'].edge_index
# for k in range(list.size(1)):
#     if k ==3: print(list[0][1355].item())
#     if list[0][k].item() == 12:
#         print(list[1][k].item())

In [56]:
# from gensim.models import Word2Vec
# from itertools import *
# dimen = 256
# window = 5

# def read_random_walk_corpus():
#     walks, node_ids = [], []
#     with open("data/het_neigh_train.txt", 'r') as file:
#         lines = file.readlines()
#         for line in lines:
#             parts = line.strip().split(':')
#             node_ids.append(parts[0])
#             path = parts[1].split(',')
#             walks.append(path)

#     return walks, node_ids

# walk_corpus, node_ids = read_random_walk_corpus()

# # Train the Word2Vec model
# model = Word2Vec(walk_corpus, vector_size=dimen, window=window, min_count=0, workers=8, sg=1, hs=0, negative=5)

# # Save node embeddings to a text file
# with open("data/node_net_embedding.txt", 'w') as file:
#     for i, node_id in enumerate(node_ids):
#         if node_id in model.wv:
#             embedding = model.wv[node_id]
#             embedding_str = " ".join(str(val) for val in embedding)
#             file.write(node_id + " " + embedding_str + "\n")
#         else:
#             print(f"Warning: Node '{node_id}' not present in the vocabulary.")
# model.wv.save_word2vec_format("data/node_net_embedding.txt")

In [6]:
with open("data/node_net_embedding.txt", 'r') as file:            
        lines = file.readlines()[1:]       

embed_d = 256
M_n = 9742
U_n = 610
m_net_embed = torch.zeros(M_n, embed_d, dtype=torch.float32)
u_net_embed = torch.zeros(U_n, embed_d, dtype=torch.float32)
        
for i, line in enumerate(lines):
    entries = line.strip().split()
    
    if not i: continue
    node_type = entries[0][0]
    node_id = int(entries[0][1:])
    if node_type == 'm':
        m_net_embed[node_id] = torch.tensor([float(x) for x in entries[1:]])
    elif node_type == 'u':
        u_net_embed[node_id] = torch.tensor([float(x) for x in entries[1:]])

In [10]:
print(m_net_embed.shape, u_net_embed.shape)

torch.Size([9742, 256]) torch.Size([610, 256])


In [12]:
# Function for heterogenous neighbour aggregation
def aggregate(x, edge_index, num_nodes): 
    # Separate source and target nodes from the edge index
    source_nodes, target_nodes = edge_index[0], edge_index[1]

    # Aggregate features for each neighbour using scatter_add
    # num_source = torch.max(source_nodes, dim = 0).values.item()
    aggr_features = torch.zeros(num_nodes, x.size(1))
    aggr_features.index_add_(0, source_nodes, x[target_nodes])

    # Normalize the aggregated features
    row_sum = torch.bincount(source_nodes, minlength=num_nodes).float().clamp(min=1)
    aggr_features /= row_sum.view(-1, 1)

    return aggr_features

In [13]:
m_u_list = data2['m','edge','u'].edge_index
m_embed = data2['m'].x
u_embed = aggregate(m_net_embed, m_u_list, U_n)

In [14]:
print(data2)

HeteroData(
  m={ x=[9742, 404] },
  u={ num_nodes=610 },
  (m, edge, u)={
    edge_index=[2, 100836],
    y=[100836]
  },
  (m, walk, m)={ edge_index=[2, 48620] },
  (m, walk, u)={ edge_index=[2, 29169] },
  (u, walk, m)={ edge_index=[2, 3050] },
  (u, walk, u)={ edge_index=[2, 1830] }
)


In [15]:
data2['m_net_embed'].x = m_net_embed    
data2['u_net_embed'].x = u_net_embed
data2['u_embed'].x = u_embed

In [18]:
data = torch.load('data/movlens_data.pt')
print(data)

HeteroData(
  movie={ x=[9742, 404] },
  user={ num_nodes=610 },
  (user, rates, movie)={
    edge_index=[2, 100836],
    edge_label=[100836]
  }
)


In [25]:
print(data2)

HeteroData(
  m={ x=[9742, 404] },
  u={ num_nodes=610 },
  m_net_embed={ x=[9742, 256] },
  u_net_embed={ x=[610, 256] },
  u_embed={ x=[610, 256] },
  (m, edge, u)={
    edge_index=[2, 100836],
    y=[100836]
  },
  (m, walk, m)={ edge_index=[2, 48620] },
  (m, walk, u)={ edge_index=[2, 29169] },
  (u, walk, m)={ edge_index=[2, 3050] },
  (u, walk, u)={ edge_index=[2, 1830] },
  (u, edge, m)={}
)


In [26]:
data3 = HeteroData()
data3['m_embed'].x = data2['m'].x
data3['m_net_embed'].x = data2['m_net_embed'].x
data3['m_embed'].num_nodes = 9742

data3['u_embed'].x = u_embed
data3['u_net_embed'].x = data2['u_net_embed'].x
data3['u_embed'].num_nodes = 610

data3['u', 'walk', 'm'].edge_index  = data2['u', 'walk', 'm'].edge_index 
data3['u', 'walk', 'u'].edge_index  = data2['u', 'walk', 'u'].edge_index 
data3['m', 'walk', 'm'].edge_index  = data2['m', 'walk', 'm'].edge_index 
data3['m', 'walk', 'u'].edge_index  = data2['m', 'walk', 'u'].edge_index 

data3['u','edge','m'].edge_index = data2['m','edge','u'].edge_index
data3['u','edge','m'].y = data2['m','edge','u'].y

In [27]:
torch.save(data3, 'data/ml_data.pt')

In [28]:
print(data3)

HeteroData(
  m_embed={
    x=[9742, 404],
    num_nodes=9742
  },
  m_net_embed={ x=[9742, 256] },
  u_embed={
    x=[610, 256],
    num_nodes=610
  },
  u_net_embed={ x=[610, 256] },
  (u, walk, m)={ edge_index=[2, 3050] },
  (u, walk, u)={ edge_index=[2, 1830] },
  (m, walk, m)={ edge_index=[2, 48620] },
  (m, walk, u)={ edge_index=[2, 29169] },
  (u, edge, m)={
    edge_index=[2, 100836],
    y=[100836]
  }
)


In [38]:
import torch

# Example tensors with requires_grad=True
x = torch.tensor([2.2, 3.3, 1.4], requires_grad=True)

# Clamp the tensor elements between a minimum and maximum value
clamped_tensor = torch.clamp(x, min=0.0, max=2.0)

# Use the clamped tensor in further computations
output = clamped_tensor.sum()

# Backward pass to compute gradients
output.backward()

# Gradients are now available for the input tensor x
print("Gradient of x:", x.grad)


Gradient of x: tensor([1., 0., 1.])
